apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: mc1
images:
  - name: docker.io/itzg/minecraft-bedrock-server
    newTag: latest
resources:
  - ../../base
configMapGenerator:
  - name: minecraft-bedrock-server-config
    behavior: create
    literals:
      - GAMEMODE='creative'
      - LEVEL_TYPE='default'
      - DIFFICULTY='easy'
      - LEVEL_NAME='My World'
      - LEVEL_SEED='7794572526148668328'
      - OPS='2533274949710273'
      - ALLOW_LIST='true'
      - ALLOW_LIST_USERS='Deddy:2533274949710273,Luna:2535463308445170'
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
      - op: replace
        path: /spec/volumeName
        value: minecraft-bedrock-server-mc1
  - target:
      version: v1
      kind: PersistentVolume
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
      - op: replace
        path: /spec/csi/volumeHandle
        value: minecraft-bedrock-mc1
  - target:
      version: v1
      kind: Deployment
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
  - target:
      version: v1
      kind: Service
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
      - op: add
        path: /metadata/annotations
        value:
          tailscale.com/expose: true
          tailscale.com/hostname: mc1
          tailscale.com/tags: tag:minecraft
      - op: add
        path: /metadata/labels
        value:
          tailscale.com/proxy-class: tun-access
