apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: mc1
images:
  - name: docker.io/itzg/minecraft-bedrock-server
    newTag: latest
resources:
  - ../../base
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
      - op: replace
        path: /spec/volumeName
        value: minecraft-bedrock-server-mc1
  - target:
      version: v1
      kind: PersistentVolume
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
      - op: replace
        path: /spec/csi/volumeHandle
        value: minecraft-bedrock-mc1
  - target:
      version: v1
      kind: Deployment
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
  - target:
      version: v1
      kind: Service
      name: minecraft-bedrock-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-bedrock-server-mc1
      - op: replace
        path: /spec/selector/app.kubernetes.io~1name
        value: minecraft-bedrock-server-mc1
      - op: add
        path: /metadata/annotations
        value:
          kube-vip.io/loadbalancerIPs: 10.1.1.48
          tailscale.com/expose: true
          tailscale.com/tags: tag:minecraft
          tailscale.com/hostname: mc1
