apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: itzg/minecraft-bedrock-server
    newTag: '2024.1.0'
resources:
  - ../../base
patches:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          cfargotunnel.com/cluster-tunnel: k3s-xmple-io
          cfargotunnel.com/fqdn: minecraft.xmple.io
    target:
      version: v1
      kind: Service
      name: minecraft
