apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      variant: prod
images:
  - name: docker.io/itzg/minecraft-bedrock-server
    newTag: 'latest'
resources:
  - ../../base
patches:
  - patch: |
      - op: add
        path: /metadata/annotations
        value:
          kube-vip.io/loadbalancerIPs: 10.1.1.48
          tailscale.com/expose "true"
          tailscale.com/hostname mc1
    target:
      version: v1
      kind: Service
      name: minecraft-bedrock
