apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-minecraft-bedrock-test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    namespace: minecraft
    server: {{ .Values.spec.destination.server }}
  source:
    path: bedrock-test
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      releaseName: bedrock-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
