apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft-common
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  destination:
    namespace: minecraft
    server: {{ .Values.spec.destination.server }}
  source:
    path: common
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
