---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-bedrock-container-config
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
data:
  EULA: 'true'
  #UID: '1000'
  #GID: '1000'
  TZ: 'Europe/London'
  #VERSION: '1.20'
  PACKAGE_BACKUP_KEEP: '2'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-bedrock-server-config
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
data:
  GAMEMODE: 'creative'
  LEVEL_TYPE: 'default'
  DIFFICULTY: 'easy'
  LEVEL_NAME: 'My World'
  #LEVEL_SEED: "33480944
  #OPS: '2533274949710273' # Deddy
  ALLOW_LIST: 'true'
  ALLOW_LIST_USERS: 'Deddy:2533274949710273,Luna:2535463308445170'
