apiVersion: v1
kind: ConfigMap
metadata:
  name: minecraft-container-config
  labels:
    app.kubernetes.io/name: minecraft-server
data:
  EULA: 'true'
  #UID: '1000'
  #GID: '1000'
  TZ: 'Europe/London'
  VERSION: 'LATEST'
  EMIT_SERVER_TELEMETRY: 'false'
  ENABLE_LAN_VISIBILITY: 'true'
  PACKAGE_BACKUP_KEEP: '2'
