apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: docker.io/itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: TZ
              value: Europe/London
            - name: VERSION
              value: LATEST
            - name: EMIT_SERVER_TELEMETRY
              value: 'false'
            - name: ENABLE_LAN_VISIBILITY
              value: 'true'
            - name: PACKAGE_BACKUP_KEEP
              value: '2'
            - name: VIEW_DISTANCE
              value: '32'
          envFrom:
            - configMapRef:
                name: minecraft-server-config
          ports:
            - containerPort: 19132
              protocol: UDP
              name: bedrock-udp
            - containerPort: 19132
              protocol: TCP
              name: bedrock-tcp
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 1Gi
          livenessProbe:
            initialDelaySeconds: 120
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                - 127.0.0.1
          tty: true
          stdin: true
          volumeMounts:
            - name: data
              mountPath: /data
      hostNetwork: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-server
