apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
#  annotations:
#    reloader.stakater.com/auto: "true"
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: docker.io/itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-container-config
            - configMapRef:
                name: minecraft-server-config
          ports:
            - containerPort: 19132
              protocol: UDP
              name: bedrock-udp
            - containerPort: 19132
              protocol: TCP
              name: bedrock-tcp
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 1Gi
          livenessProbe:
            initialDelaySeconds: 120
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                - 127.0.0.1
          tty: true
          stdin: true
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-server
