apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: minecraft
resources:
  - storage.yaml
  - config.yaml
  - deployment.yaml
  - service.yaml
