apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: minecraft
resources:
  - storage.yaml
#  - config.yaml
  - deployment.yaml
  - service.yaml
generatorOptions:
  disableNameSuffixHash: false
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
configMapGenerator:
  - name: minecraft-bedrock-container-config
    behavior: create
    literals:
      - EULA='true'
      - TZ='Europe/London'
      - VERSION='LATEST'
      - EMIT_SERVER_TELEMETRY='false'
      - ENABLE_LAN_VISIBILITY='true'
      - PACKAGE_BACKUP_KEEP='2'
