apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock-server
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
spec:
  selector:
    app.kubernetes.io/name: minecraft-bedrock-server
  ports:
    - name: bedrock
      protocol: UDP
      port: 19132
      targetPort: bedrock
    - name: bedrock
      protocol: TCP
      port: 19132
      targetPort: bedrock
  type: LoadBalancer