apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock-server
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
spec:
  selector:
    app.kubernetes.io/name: minecraft-bedrock-server
  ports:
    - port: 19132
      protocol: UDP
  type: LoadBalancer