---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft-server
  annotations:
    lbipam.cilium.io/ips: "10.1.1.52"
    lbipam.cilium.io/sharing-key: minecraft-lb
spec:
  selector:
    app.kubernetes.io/name: minecraft-server
  ports:
    - name: bedrock-udp
      protocol: UDP
      port: 19132
      targetPort: bedrock-udp
    - name: bedrock-tcp
      protocol: TCP
      port: 19132
      targetPort: bedrock-tcp
  type: LoadBalancer
  loadBalancerClass: io.cilium/l2-announcer
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server-ts
  labels:
    app.kubernetes.io/name: minecraft-server-ts
spec:
  selector:
    app.kubernetes.io/name: minecraft-server
  ports:
    - name: bedrock-udp
      protocol: UDP
      port: 19132
      targetPort: bedrock-udp
    - name: bedrock-tcp
      protocol: TCP
      port: 19132
      targetPort: bedrock-tcp
  type: LoadBalancer
  loadBalancerClass: tailscale