apiVersion: v1
kind: Service
metadata:
  name: minecraft-bedrock-server
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
spec:
  selector:
    app.kubernetes.io/name: minecraft-bedrock-server
  ports:
    - name: bedrock-udp
      protocol: UDP
      port: 19132
      targetPort: bedrock-udp
    - name: bedrock-tcp
      protocol: TCP
      port: 19132
      targetPort: bedrock-tcp
  type: LoadBalancer