---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: minecraft-storage-class
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: minecraft-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: minecraft-server
  storageClassName: minecraft-storage-class
