---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-bedrock-server
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-minecraft
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: minecraft-bedrock-server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock-server
  labels:
    app.kubernetes.io/name: minecraft-bedrock-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: minecraft-bedrock-server
  storageClassName: longhorn-minecraft
