---
apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: minecraft-server
spec:
  blocks:
    - start: "10.1.1.52"
  serviceSelector:
    matchLabels:
      io.kubernetes.service.namespace: minecraft
