kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: minecraft-storage-class
provisioner: driver.longhorn.io
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  fsType: "ext4"
