apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: mc2
images:
  - name: docker.io/itzg/minecraft-bedrock-server
    newTag: latest
resources:
  - ../../base
configMapGenerator:
  - name: minecraft-server-config
    behavior: create
    literals:
      - GAMEMODE='creative'
      - LEVEL_TYPE='default'
      - DIFFICULTY='easy'
      - LEVEL_NAME='My Empty World'
      - LEVEL_SEED='7794572526148668328'
      - OPS='2533274949710273'
      - ALLOW_LIST='true'
      - ALLOW_LIST_USERS='Deddy:2533274949710273,Luna:2535463308445170'
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: minecraft-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-server-mc2
      - op: replace
        path: /spec/volumeName
        value: minecraft-server-mc2

  - target:
      version: v1
      kind: PersistentVolume
      name: minecraft-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-server-mc2
      - op: replace
        path: /spec/csi/volumeHandle
        value: minecraft-server-mc2

  - target:
      version: v1
      kind: Deployment
      name: minecraft-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-server-mc2

  - target:
      version: v1
      kind: Service
      name: minecraft-server
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-server-mc2
      - op: replace
        path: /spec/ports/0/port
        value: 19133
      - op: replace
        path: /spec/ports/1/port
        value: 19133

  - target:
      version: v1
      kind: Service
      name: minecraft-server-ts
    patch: |
      - op: replace
        path: /metadata/name
        value: minecraft-server-ts-mc2
      - op: add
        path: "/metadata/annotations/tailscale.com/hostname"
        value: mc2
