apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/instance: mc2
images:
  - name: docker.io/itzg/minecraft-bedrock-server
    newTag: latest
resources:
  - ../../base
configMapGenerator:
  - name: minecraft-server-config-mc2
    behavior: create
    options:
      disableNameSuffixHash: true
    literals:
      - SERVER_NAME='My World 2'
      - SERVER_PORT='19232'
      - SERVER_PORT_V6='19233'
      - GAMEMODE='creative'
      - LEVEL_TYPE='default'
      - DIFFICULTY='easy'
      - LEVEL_NAME='My World'
      #- LEVEL_SEED='7794572526148668328'
      - OPS='2533274949710273'
      - ALLOW_LIST='true'
      - ALLOW_LIST_USERS='Deddy:2533274949710273,Luna:2535463308445170'
patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: minecraft-server
    options:
      allowNameChange: true
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: minecraft-server-mc2
      spec:
        volumeName: minecraft-server-mc2

  - target:
      version: v1
      kind: PersistentVolume
      name: minecraft-server
    options:
      allowNameChange: true
    patch: |-
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: minecraft-server-mc2
      spec:
        csi:
          volumeHandle: minecraft-server-mc2

  - target:
      version: v1
      kind: Deployment
      name: minecraft-server
    options:
      allowNameChange: true
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: minecraft-server-mc2
        annotations:
          reloader.stakater.com/auto: "true"
      spec:
        template:
          spec:
            containers:
              - name: minecraft-server
                $patch: merge
                envFrom:
                  - configMapRef:
                      name: minecraft-server-config-mc2
                $patch: replace
                ports:
                  - name: bedrock-udp
                    containerPort: 19232
                    protocol: UDP
                  - name: bedrock-tcp
                    containerPort: 19232
                    protocol: TCP

  - target:
      version: v1
      kind: Service
      name: minecraft-server
    options:
      allowNameChange: true
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: minecraft-server-mc2
      spec:
        $patch: replace
        ports:
          - name: bedrock-tcp
            protocol: TCP
            port: 19133
            targetPort: bedrock-tcp
          - name: bedrock-udp
            protocol: UDP
            port: 19133
            targetPort: bedrock-udp

  - target:
      version: v1
      kind: Service
      name: minecraft-server-ts
    options:
      allowNameChange: true
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: minecraft-server-ts-mc2
        annotations:
          tailscale.com/hostname: mc2
