apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock
  labels:
    app.kubernetes.io/name: minecraft-bedrock
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-bedrock
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-bedrock
    spec:
      containers:
        - name: minecraft-bedrock
          image: docker.io/itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: minecraft-bedrock-container-config
            - configMapRef:
                name: minecraft-bedrock-server-config
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1
              memory: 1Gi
          readinessProbe: &probe
            initialDelaySeconds: 30
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                - 127.0.0.1
          livenessProbe: *probe
          tty: true
          stdin: true
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-bedrock
