apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock-1
  labels:
    app.kubernetes.io/name: minecraft-bedrock-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-bedrock-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-bedrock-1
    spec:
      containers:
        - name: minecraft-bedrock
          image: docker.io/itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: EULA
              value: "TRUE"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-bedrock-1