apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-bedrock-1
  labels:
    app.kubernetes.io/name: minecraft-bedrock-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-bedrock-1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-bedrock-1
    spec:
      containers:
        - name: minecraft-bedrock
          image: docker.io/itzg/minecraft-bedrock-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
          envFrom:
            - configMapRef:
                name: minecraft-bedrock-1-config
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          readinessProbe: &probe
            exec:
              command:
                - mc-monitor
                - status-bedrock
                - --host
                # force health check against IPv4 port
                - 127.0.0.1
            initialDelaySeconds: 30
          livenessProbe: *probe
          tty: true
          stdin: true
          volumeMounts:
            - name: data
              mountPath: /data
            - name: allowlist
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minecraft-bedrock-1
        - name: allowlist
          configMap:
            name: minecraft-allowlist-config