apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: minecraft
  app.kubernetes.io/part-of: minecraft
resources:
  - storage.yaml
  - deployment.yaml
  - service.yaml
