---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-bedrock
  labels:
    app.kubernetes.io/name: minecraft-bedrock
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-minecraft
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: minecraft-bedrock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-bedrock
  labels:
    app.kubernetes.io/name: minecraft-bedrock
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumeName: minecraft-bedrock
  storageClassName: longhorn-minecraft
